---
name: PR validation
on:
  pull_request:

jobs:
  validate:
    uses: AdobeDocs/commerce-contributor/.github/workflows/validate-pr.yml@main
    with:
      base_ref: ${{ github.event.pull_request.base.ref }}
